// Historical figure/layout definitions from the September 7 redesign.
// Rendering context and required assets are supplied by the caller.
// This archive is not the scientific reproduction entry point.
import fs from 'node:fs/promises';
export async function addHistoricalFigures({presentation, computed, equations, assetsDir}) {
const p=presentation, data=computed, E=equations, B=assetsDir, OLD=assetsDir, manifest=[];
const C={ink:'#16313F',gray:'#53656F',light:'#E5EBEE',blue:'#0072B2',orange:'#E69F00',green:'#009E73',pink:'#CC79A7',cyan:'#56B4E9'};
const colors=[C.blue,C.orange,C.green,C.pink,C.cyan];
const ref={prive:['Privé et al. (2020), Bioinformatics','https://doi.org/10.1093/bioinformatics/btaa520'],bigsnpr:['bigsnpr PCA documentation','https://privefl.github.io/bigsnpr/articles/bedpca.html'],price:['Price et al. (2006), Nature Genetics','https://doi.org/10.1038/ng1847'],patterson:['Patterson et al. (2006), PLoS Genetics','https://doi.org/10.1371/journal.pgen.0020190'],lawson:['Lawson et al. (2018), Nature Communications','https://doi.org/10.1038/s41467-018-05257-7'],sharma:['Sharma et al. (2025), Nature Communications','https://doi.org/10.1038/s41467-025-59351-8'],ldsc:['Bulik-Sullivan et al. (2015a), Nature Genetics','https://doi.org/10.1038/ng.3211'],hu:['Hu et al. (2025), Nature Genetics','https://doi.org/10.1038/s41588-024-02035-8'],ding:['Ding et al. (2023), Nature','https://doi.org/10.1038/s41586-023-06079-4'],rare:['Hanson et al. (2026), Nature Communications','https://doi.org/10.1038/s41467-026-73776-9'],moba:['Corfield et al. (2026), Nature','https://doi.org/10.1038/s41586-026-10926-5'],family:['Guan et al. (2025), Nature Genetics','https://doi.org/10.1038/s41588-025-02118-0'],tan:['Tan et al. (2026), Nature Genetics','https://doi.org/10.1038/s41588-026-02689-6'],kang:['Kang et al. (2010), Nature Genetics','https://doi.org/10.1038/ng.548'],devlin:['Devlin & Roeder (1999), Biometrics','https://doi.org/10.1111/j.0006-341X.1999.00997.x']};
ref.prive22=['Privé et al. (2022), American Journal of Human Genetics','https://doi.org/10.1016/j.ajhg.2021.11.008'];
ref.li=['Li et al. (2008), Science','https://doi.org/10.1126/science.1153717'];
ref.jakobsson=['Jakobsson et al. (2008), Nature','https://doi.org/10.1038/nature06742'];
function txt(s,t,x=80,y=180,w=1120,h=70,size=32,opt={}){const o=s.shapes.add({name:opt.name||t.slice(0,70)||'Text',geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});o.text=t;o.text.style={typeface:opt.font||'Calibri',fontSize:size,color:opt.color||C.ink,bold:opt.bold||false,alignment:opt.align||'left',verticalAlignment:'top',autoFit:'none',wrap:'square',insets:{left:0,right:0,top:0,bottom:0}};return o;}
function shape(s,g,x,y,w,h,fill=C.light,line='none'){return s.shapes.add({name:g,geometry:g,position:{left:x,top:y,width:w,height:h},fill,line:{fill:line,width:line==='none'?0:2}})}
function line(s,x1,y1,x2,y2,color=C.gray,width=2,dashed=false){const x=Math.min(x1,x2),y=Math.min(y1,y2),w=Math.max(Math.abs(x2-x1),.1),h=Math.max(Math.abs(y2-y1),.1);return s.shapes.add({name:'Calculated line',geometry:'custom',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:color,width,style:dashed?'dashed':'solid'},customPaths:[{width:w,height:h,commands:[{moveTo:{x:x1-x,y:y1-y}},{lineTo:{x:x2-x,y:y2-y}}]}]});}
function arrow(s,x1,y1,x2,y2,color=C.gray){line(s,x1,y1,x2,y2,color,2.5);let a=Math.atan2(y2-y1,x2-x1);for(const b of [a+.45,a-.45])line(s,x2,y2,x2-12*Math.cos(b),y2-12*Math.sin(b),color,2.5);}
function slide(key,title,{replace,after,notes='',sources=[],section='POPULATION STRUCTURE'}={}){const s=p.slides.add();s.background.fill='#FFFFFF';txt(s,title,80,43,1120,99,44,{name:'Deck title',bold:true});line(s,80,145,1200,145,C.light,2);txt(s,section,80,17,1000,23,15,{color:C.gray,name:'Section marker'});if(sources.length){const a=txt(s,sources.map(k=>ref[k][0]).join(';  '),80,687,1120,25,18,{color:C.gray,name:'Reference citation'});for(const k of sources)a.text.get(ref[k][0]).link={uri:ref[k][1],isExternal:true};}let m={key,title,replace,after,notes,sources,references:sources.map(k=>ref[k]),donorSlide:p.slides.items.length,equations:[],tables:0,charts:0};s.meta=m;manifest.push(m);return s;}
function caption(s,n,t){txt(s,`Figure ${n}. ${t}`,80,650,1120,31,22,{color:C.gray,name:'Figure caption'});}
async function eq(s,key,y,{x=92,w=1060,maxH=150,scale=3.7}={}){const e=E[key],k=Math.min(scale,w/e.width,maxH/e.height);s.images.add({blob:new Uint8Array(await fs.readFile(e.file)),contentType:'image/svg+xml',alt:`Equation ${e.number}. ${e.latex}`,fit:'contain',position:{left:x,top:y,width:e.width*k,height:e.height*k}});txt(s,`(${e.number})`,1160,y+Math.max(0,(e.height*k-30)/2),44,35,24,{align:'right'});s.meta.equations.push(key);return e.height*k;}
async function pic(s,file,x,y,w,h,alt,crop){s.images.add({blob:new Uint8Array(await fs.readFile(file)),contentType:file.endsWith('.svg')?'image/svg+xml':'image/png',alt,fit:crop?'cover':'contain',...(crop?{crop}:{}),position:{left:x,top:y,width:w,height:h}});if(crop)(s.meta.crops??=[]).push({alt,crop,frame:[x,y,w,h],imageIndex:s.images.items.length-1});}
function table(s,values,x,y,w,h,widths,size=24){const t=s.tables.add({rows:values.length,columns:values[0].length,left:x,top:y,width:w,height:h,columnWidths:widths,values});t.styleOptions={headerRow:false,bandedRows:false};t.cells.block({row:0,column:0,rowCount:values.length,columnCount:values[0].length}).assign({fill:'#FFFFFF',textStyle:{typeface:'Calibri',fontSize:size,color:C.ink},margins:{left:10,right:10,top:4,bottom:4},anchor:'center'});t.borders.assign({fill:C.light,width:.7,style:'solid'});for(let j=0;j<values[0].length;j++){t.getCell(0,j).fill=C.light;t.getCell(0,j).text.style={typeface:'Calibri',fontSize:size,bold:true,color:C.ink};}s.meta.tables++;return t;}
const axis=(title,min,max,format='0.0')=>({title:{text:title,textStyle:{typeface:'Calibri',fontSize:22,fill:C.ink}},min,max,numberFormatCode:format,textStyle:{typeface:'Calibri',fontSize:20,fill:C.gray},line:{fill:C.gray,width:1},majorGridlines:{fill:C.light,width:.7},minorGridlines:null});
function series(name,x,y,color,point=true,width=2){return {name,xValues:x,values:y,fill:color,line:{fill:point?'none':color,width:point?0:width},marker:{symbol:point?'circle':'none',size:4}};}
function chart(s,ser,x,y,w,h,{xt='',yt='',xmin,xmax,ymin,ymax,title='',legend=false,xformat='0.0',yformat='0.0'}={}){const ch=s.charts.add('scatter',{position:{left:x,top:y,width:w,height:h},title,titlePlacement:title?'aboveChart':'none',titleTextStyle:{typeface:'Calibri',fontSize:26,fill:C.ink,bold:true},series:ser,scatterOptions:{style:'lineWithMarkers'},hasLegend:legend,legend:{position:'bottom',overlay:false,textStyle:{typeface:'Calibri',fontSize:20,fill:C.ink}},xAxis:axis(xt,xmin,xmax,xformat),yAxis:{...axis(yt,ymin,ymax,yformat),...(yt===''?{visible:false,majorGridlines:null}: {})},chartFill:'#FFFFFF',chartLine:{fill:'none',width:0},plotAreaFill:'#FFFFFF',plotAreaLine:{fill:'none',width:0}});s.meta.charts++;return ch;}
function grouped(points,groups,names=['Group A','Group B'],palette=[C.blue,C.orange]){return names.map((name,q)=>{let ix=groups.map((g,i)=>g===q?i:-1).filter(i=>i>=0);return series(name,ix.map(i=>points[i][0]),ix.map(i=>points[i][1]),palette[q]);});}
function key(s,labels,x,y,palette=colors){labels.forEach((t,i)=>{shape(s,'ellipse',x+i*210,y+5,15,15,palette[i]);txt(s,t,x+25+i*210,y,175,30,23);});}
function question(s,t,y=576){txt(s,t,80,y,1120,65,30,{bold:true,color:C.green});}
const notation='Notation throughout: M variants in rows, N individuals in columns; i focal SNP, j individual, k PC, q reference population. G is raw dosage, X centered or standardized dosage, Psi=X^T X/M. V contains individual unit eigenvectors, D contains eigenvalues d_k. PC scores multiply v_k by sqrt(M*d_k). Eigenvector signs are arbitrary. Software bigsnpr stores individuals in rows, the transpose of the lecture convention.';
const simNotes='Synthetic, reproducible teaching example generated with R 4.6.0, bigstatsr 1.6.2 and bigsnpr 1.12.21; seed 20260907. N=600, M=3000 independent background SNPs. Group a_j in {0,1}. Background frequencies differ by 0.13; focal null SNP frequencies 0.2 and 0.6. True causal SNP frequency 0.4 in both groups, effect 0.25. Phenotype pi_j=1.2(a_j-0.5)+0.25*g_causal,j+epsilon_j with independent N(0,1) errors. Focal SNPs are excluded from PC computation. PCs computed from binomial-standardized background genotypes. Point estimates and 95% t confidence intervals are calculated from full regression with N-K-2 residual degrees of freedom. A single simulated realization does not establish general calibration. All 600 individuals are plotted; horizontal jitter changes only display positions. ';

// The same concrete genotype matrix now anchors the entire PCA explanation.
{
let s=slide('one_genotype','One genotype example for the whole PCA sequence',{replace:16,section:'MEASURING STRUCTURE',notes:notation+' The raw-correlation illustration from the previous deck is retained in the appendix.'});
txt(s,'Seven SNPs × five individuals',80,176,620,45,32,{bold:true});
let t=table(s,[['SNP','Ind 1','Ind 2','Ind 3','Ind 4','Ind 5'],...data.small.G.map((r,i)=>[String(i+1),...r.map(String)])],80,237,675,337,[90,117,117,117,117,117],26);
for(let j=1;j<=5;j++){t.getCell(0,j).fill=colors[j-1];t.getCell(0,j).text.style={typeface:'Calibri',fontSize:25,bold:true,color:'#FFFFFF'};}
txt(s,'G → X → Ψ → V',815,260,385,75,40,{bold:true});txt(s,'Raw dosages\nCenter each SNP\nCompare individuals\nFind the principal axes',815,360,385,250,31);
txt(s,'Table 7. The same five individuals retain their colors throughout.',80,612,1120,32,23,{color:C.gray});
}
for(let step=0;step<5;step++){
let title=['PCA geometry: the same five individuals','PC1 follows the greatest variation','Project each individual onto PC1','PC2 is perpendicular to PC1','PC scores and unit eigenvectors'][step];
let s=slide('geometry_'+step,title,{replace:19+step,section:'MEASURING STRUCTURE',sources:['patterson'],notes:notation+' Figure 9 is calculated from the seven-SNP example. The two-dimensional view is the leading PC plane rotated by 0.52 radians for display; omitted PCs are not shown. Lines are perpendicular projections, not hand-placed schematic eigenvectors.'});
const ox=428,oy=389,scale=87,ax=data.small.axes;
if(step===0){line(s,120,oy,740,oy,C.light,1);line(s,ox,180,ox,600,C.light,1);}
for(let k=0;k<(step===0?0:step<3?1:2);k++){const [dx,dy]=[ax[0][k],ax[1][k]],r=k===0?3.25:2.1;arrow(s,ox-r*scale*dx,oy+r*scale*dy,ox+r*scale*dx,oy-r*scale*dy,k===0?C.ink:C.gray);txt(s,'PC'+(k+1),ox+r*scale*dx+6,oy-r*scale*dy-10,90,36,26,{bold:true});}
if(step>=2)for(let j=0;j<5;j++){let [xx,yy]=data.small.geometry[j],d=data.small.score[j][0],px=d*ax[0][0],py=d*ax[1][0];line(s,ox+scale*xx,oy-scale*yy,ox+scale*px,oy-scale*py,colors[j],1.5,true);shape(s,'ellipse',ox+scale*px-5,oy-scale*py-5,10,10,colors[j]);}
for(let j=0;j<5;j++){let [xx,yy]=data.small.geometry[j];shape(s,'ellipse',ox+scale*xx-9,oy-scale*yy-9,18,18,colors[j]);txt(s,String(j+1),ox+scale*xx+12,oy-scale*yy-13,40,35,26,{bold:true,color:colors[j]});}
let msg=[['A two-dimensional view of the leading PC plane.','Each point is one column of G.'],['PC1 accounts for 78.7% of the total centered variation.','The axis passes through the centered origin.'],['The dashed segments meet PC1 at right angles.','The projected coordinate is the PC1 score.'],['PC2 accounts for another 12.0% of the variation.','Orthogonal axes capture different directions.'],['Scores include the singular-value scale.','Unit eigenvectors have squared entries summing to one.']][step];
txt(s,msg[0],805,208,390,155,32,{bold:true});txt(s,msg[1],805,408,390,135,30);
if(step===4){txt(s,'Ind 1: score = '+data.small.score[0][0].toFixed(3)+'\nv₁ coordinate = '+data.small.V[0][0].toFixed(3),805,552,390,77,27);}
caption(s,9,'Calculated projections of the seven-SNP example; point numbers identify individuals.');
}
{
let s=slide('dimension_guide','Keep dimensions, eigenvectors and scores distinct',{after:25,section:'MEASURING STRUCTURE',notes:notation,sources:['patterson','prive']});
table(s,[['Object','Dimensions','Meaning'],['G, X','M × N','SNP rows; individual columns'],['Ψ','N × N','Similarity between individuals'],['Vₖ','N × K','K unit eigenvectors'],['VₖSₖ','N × K','Individual PC scores']],80,180,1120,290,[200,230,690],27);
await eq(s,'scores',506,{maxH:65,scale:3.3});txt(s,'Table 8. Multiplying a PC by a nonzero constant does not change its adjustment space.',80,609,1120,36,24,{color:C.gray});
}
// Native chromosomes link local labels to genome-wide proportions.
function chromosomes(s,y,{offset=0,large=true}={}){let x=270,w=large?760:550,h=large?44:32;let a1=[1,1,1,1,1,0,0,0],a2=[1,1,1,0,0,0,0,0];if(offset){a1=[0,0,1,1,1,1,1,0];a2=[0,0,0,1,1,1,0,0];}for(let hidx=0;hidx<2;hidx++){let arr=hidx?a2:a1;txt(s,'Copy '+(hidx+1),80,y+hidx*(h+24)+5,170,45,28);for(let b=0;b<8;b++)shape(s,'rect',x+b*w/8,y+hidx*(h+24),w/8-.8,h,arr[b]?C.blue:C.orange);}return{x,w,h};}
{
let s=slide('local_global','Local ancestry labels add up to global ancestry',{after:43,section:'ANCESTRY INFERENCE',sources:['tan'],notes:'Figure 28 is an editable teaching diagram, not an inferred chromosome. Eight equally long segments on each of two chromosome copies: 8 of 16 copy-segments are assigned reference ancestry 1. Global ancestry is length-weighted over the specified genomic region; real segment lengths differ and local ancestry inference is uncertain. L is haploid analyzed length, L_b segment length, h chromosome copy, and A_jhb reference label. Same global proportion can correspond to different local mosaics.'});
txt(s,'One diploid region: eight equally long segments per copy',80,176,1120,44,31);let b=chromosomes(s,256);key(s,['Reference 1','Reference 2'],340,424,[C.blue,C.orange]);txt(s,'8 of 16 copy-segments → global proportion α = 0.50',80,469,1120,50,34,{bold:true});await eq(s,'global',530,{maxH:103,scale:3.3});caption(s,28,'Local ancestry along two copies; global ancestry averages over their lengths.');
}
// Original publisher panels: exact data and legends, larger than in v1.
{
let s=slide('ding_large','PGS accuracy varies along a genetic continuum',{replace:13,sources:['ding'],notes:'Original Figure 3b from Ding et al. (2023), cropped from the full-resolution publisher figure. The vertical axis is the paper\'s model-based individual-level relative accuracy, not a directly measured single-person R-squared. The published notation and group labels are retained inside the source figure. Source image and complete caption are linked via the article.'});
await pic(s,B+'/ding-fig3-full.png',80,215,1120,297,'Figure 7. Ding et al. (2023), published Figure 3b, with its complete axes and legend',{left:0,top:.37,right:0,bottom:.325});
txt(s,'Accuracy changes within broad ancestry labels as well as between them.',80,567,1120,54,32,{bold:true});caption(s,7,'Height PGS: model-based relative accuracy versus distance from the training population.');
}
{
let s=slide('hu_large','Fine-scale ancestry can matter after PC adjustment',{replace:42,sources:['hu'],notes:'Original Figure 3c of Hu et al. (2025), enlarged from the publisher asset. Each point is a reported GWAS signal, colored according to the original legend. Vertical axis -log10(P_PC); horizontal axis -log10(P_AC). Large vertical values with smaller horizontal values illustrate birthplace associations attenuated with ancestry components. The panel does not by itself show that every removed association is a false causal signal. The full original figure, legend and methods remain linked.'});
await pic(s,B+'/hu-fig3-full.png',145,175,386,416,'Figure 12. Hu et al. Figure 3c, birthplace north/south, original axes',{left:0,top:.515,right:.656,bottom:.062});
await pic(s,B+'/hu-fig3-full.png',80,599,1120,45,'Original Hu et al. trait-category legend',{left:0,top:.955,right:0,bottom:0});
txt(s,'Birthplace is a diagnostic phenotype for geographical structure.',768,189,427,123,32,{bold:true});txt(s,'Some signals weaken when the model uses finer ancestry components (ACs).',768,356,427,150,31);txt(s,'ACs do not replace modelling close relatives.',768,533,427,74,28,{color:C.green,bold:true});caption(s,12,'Published birthplace comparison: PCs on the vertical axis, ACs on the horizontal axis.');
}
{
let s=slide('clustering_refs','The reference panel changes the inferred components',{after:51,section:'ANCESTRY INFERENCE',sources:['lawson'],notes:'Figure 27 is a synthetic supervised likelihood demonstration, not STRUCTURE or ADMIXTURE output. Thirty diploid genomes at 1,200 independent SNPs are generated from three distinct frequency profiles (10 per profile). Profile C has intermediate A/B frequencies plus independent drift. The same genotypes are fit by maximizing a binomial mixture likelihood over a simplex grid: three known reference profiles versus A/B only. A mixed bar is not proof of a recent admixture history. Frequency profiles, random seeds and fitted proportions are saved in the build provenance.'});
txt(s,'The same 30 genomes, in the same order',80,176,1120,44,31,{bold:true});
for(let r=0;r<2;r++){let y=258+r*174;txt(s,r?'References A + B':'References A + B + C',80,y+27,240,96,27,{bold:true});let q=r?data.clustering.reduced:data.clustering.full;for(let j=0;j<30;j++){let bottom=y+113;for(let c=0;c<3;c++){let h=q[j][c]*112;shape(s,'rect',345+j*27.5,bottom-h,25,h,[C.blue,C.orange,C.green][c]);bottom-=h;}}for(let k=0;k<3;k++)txt(s,'Profile '+['A','B','C'][k],345+k*275,y+122,270,32,24,{align:'center'});}
question(s,'Would you call the green-profile individuals recently admixed?',600);caption(s,27,'Computed reference-panel sensitivity; colors are fitted components.');
}
{
let s=slide('allofus_plot','All of Us: a continuous cloud with dense regions',{replace:52,section:'ANCESTRY INFERENCE',sources:['sharma'],notes:'Original Figure 1c of Sharma et al. (2025), full-resolution crop, shows 7 density-defined PCA groups. The study separately identified 13 UMAP groups, illustrating dependence on representation and resolution. N=297,549 in the analyzed controlled-tier array-data sample (v7); this is not the whole All of Us program. Participants self-identifying as American Indian/Alaska Native were excluded from the analyzed release. Published group colors do not define discrete biological types. The original numerical comparison is retained in the appendix.'});
await pic(s,B+'/sharma-fig1-full.png',120,190,1040,454,'Figure 29. All of Us published Figure 1c, PC1/PC2 and PC1/PC3 groups',{left:0,top:.666,right:0,bottom:0});
caption(s,29,'7 PCA density groups shown; a separate UMAP analysis identified 13 groups.');
}
// A running GWAS example starts here, then returns after residualization.
{
let s=slide('running_setup','A running example: no direct effect at the tested SNP',{after:59,section:'POPULATION STRATIFICATION',sources:['price'],notes:simNotes});
const nodes=[txt(s,'Group / ancestry',470,200,300,62,32,{bold:true,align:'center'}),txt(s,'Null SNP dosage',100,365,350,68,32,{bold:true,align:'center'}),txt(s,'Environmental shift',793,365,400,68,32,{bold:true,align:'center'}),txt(s,'Phenotype π',480,510,300,68,32,{bold:true,align:'center'})];
s.shapes.connect(nodes[0],nodes[1],{kind:'straight',fromSide:'left',toSide:'top',line:{fill:C.gray,width:2},tail:{type:'arrow'}});s.shapes.connect(nodes[0],nodes[2],{kind:'straight',fromSide:'right',toSide:'top',line:{fill:C.gray,width:2},tail:{type:'arrow'}});s.shapes.connect(nodes[2],nodes[3],{kind:'straight',fromSide:'bottom',toSide:'right',line:{fill:C.gray,width:2},tail:{type:'arrow'}});
txt(s,'Allele frequency:\n0.20 in A; 0.60 in B',97,445,350,100,27);txt(s,'Mean difference: 1.2',900,487,298,70,25);txt(s,'600 people; 3,000 background SNPs; separate causal SNP effect = 0.25',80,597,1120,42,26);caption(s,23,'Synthetic data with an ancestry-associated environment and a known null SNP.');
}
{
let s=slide('running_apparent','The null SNP appears associated in the pooled sample',{after:59,section:'POPULATION STRATIFICATION',notes:simNotes});let r=data.running;
const pts=r.genotype.map((g,j)=>[g+r.jitter[j],r.phenotype[j]]);
chart(s,grouped(pts,r.ancestry),80,183,747,414,{xt:'Null SNP dosage (jittered)',yt:'Phenotype π',xmin:-.25,xmax:2.25,ymin:-4,ymax:4});key(s,['Group A','Group B'],247,600,[C.blue,C.orange]);
txt(s,'True effect: 0',875,214,310,60,34,{bold:true});txt(s,'Estimated effect\n0.375\n95% CI [0.248, 0.501]',875,306,315,178,30);txt(s,'P = 1.0 × 10⁻⁸',875,532,315,52,31,{bold:true,color:C.green});caption(s,24,'Same simulated individuals; the pooled association tags the environmental difference.');
}
{
let s=slide('running_pcs','PC1 identifies the main ancestry difference',{after:59,section:'POPULATION STRATIFICATION',sources:['price','prive'],notes:simNotes+notation});
chart(s,grouped(data.running.pc,data.running.ancestry),80,185,747,422,{xt:'v₁ coordinate',yt:'v₂ coordinate',xmin:-.065,xmax:.065,ymin:-.15,ymax:.15,xformat:'0.00',yformat:'0.00'});key(s,['Group A','Group B'],247,604,[C.blue,C.orange]);
txt(s,'PC1 explains 99.1% of the variation in the group indicator in this simulation.',865,205,330,210,32,{bold:true});txt(s,'The two tested SNPs were excluded when fitting the PCs.',865,463,330,145,29);caption(s,25,'PCA of the background genotypes from the same 600 individuals.');
}
{
let s=slide('running_adjusted','After PC adjustment, compare residual with residual',{after:82,section:'ACCOUNTING FOR STRUCTURE',sources:['price'],notes:simNotes+' The residuals shown come from projection on the intercept and PC1. Residualizing only the phenotype is not equivalent to the full SNP-plus-PC model.'});let r=data.running;
chart(s,grouped(r.residualG.map((g,j)=>[g,r.residualPi[j]]),r.ancestry),80,184,747,420,{xt:'Residual SNP dosage',yt:'Residual phenotype',xmin:-1.5,xmax:2,ymin:-4,ymax:4});key(s,['Group A','Group B'],247,604,[C.blue,C.orange]);
txt(s,'Estimated effect\n−0.083\n95% CI [−0.213, 0.047]',865,220,330,206,31,{bold:true});txt(s,'P = 0.21\nTrue effect: 0',865,480,330,113,31);caption(s,26,'Both vectors are adjusted for the intercept and PC1; the same individuals remain.');
}
function intervalSeries(rows,truths){let ss=[];truths.forEach((t,i)=>ss.push(series('Truth '+i,[t,t],[.5,rows.length+.5],C.gray,false,1.5)));rows.forEach((r,i)=>{let yy=rows.length-i;ss.push(series(r.label+' 95% CI',[r.low,r.high],[yy,yy],r.color,false,3));let b=series(r.label,[r.beta],[yy],r.color,true);b.marker.size=9;b.dataLabelOverrides=[{idx:0,text:r.label,position:'top',textStyle:{typeface:'Calibri',fontSize:22,fill:C.ink}}];ss.push(b);});return ss;}
{
let s=slide('running_truth','Adjustment removes the spurious signal and retains the causal signal',{after:82,section:'ACCOUNTING FOR STRUCTURE',notes:simNotes});let rr=data.running;
for(let q=0;q<2;q++){let a=q?rr.causal:rr.null;let rows=[{...a[0],label:'Unadjusted',color:C.orange},{...a[1],label:'PC1 adjusted',color:C.blue}];chart(s,intervalSeries(rows,[q?.25:0]),70+q*615,195,580,366,{title:q?'Causal SNP: truth = 0.25':'Null SNP: truth = 0',xt:'Estimated effect and 95% CI',yt:'',xmin:-.3,xmax:.6,ymin:.35,ymax:2.65});}
txt(s,'Assess the estimates against the target effects and their uncertainty.',80,588,1120,55,29,{bold:true});caption(s,30,'Computed estimates, 95% confidence intervals and vertical known-effect references.');
}
// Paired Q-Q and LD-score panels use the same working-model realization.
{
let s=slide('matched_qq','Similar Q–Q inflation can have different causes',{replace:69,section:'DIAGNOSING INFLATION',sources:['ldsc'],notes:'Figure 20 is computed from 100,000 independent one-df test statistics under the LDSC working model, not a full genotype GWAS. The same standard-normal draws are used in A and B. A has variance 1.4 independent of LD score. B has variance 1+0.008*ell_i with ell uniform on [5,95]. Both have expected mean chi-square 1.4. Curves display a deterministic subset of empirical quantiles, including the tail.'});
for(let q=0;q<2;q++){let z=q?data.ldsc.polyQQ:data.ldsc.confQQ;chart(s,[series('Null',[0,5.4],[0,5.4],C.gray,false,1.5),series('Observed',z.x,z.y,q?C.orange:C.blue)],70+615*q,184,580,391,{title:q?'Scenario B':'Scenario A',xt:'Expected −log₁₀(P)',yt:'Observed −log₁₀(P)',xmin:0,xmax:5.4,ymin:0,ymax:8});}
question(s,'Which scenario reflects confounding, and which reflects polygenic signal?',591);caption(s,20,'Matched simulations with expected mean χ² = 1.4 in both scenarios.');
}
{
let s=slide('matched_ldsc','The relationship with LD score separates these scenarios',{replace:71,section:'DIAGNOSING INFLATION',sources:['ldsc'],notes:'Figure 21 uses the same 100,000 simulated statistics as the paired Q-Q slide. Points are means in 20 equal-width LD-score bins. Lines show the generating conditional means, not fitted real GWAS results. OLS intercepts are approximately '+data.ldsc.confFit[0].toFixed(3)+' and '+data.ldsc.polyFit[0].toFixed(3)+'. Scenario A demonstrates LD-independent confounding under the LDSC working model, whereas scenario B demonstrates an LD-dependent polygenic component. The contrast relies on the assumed confounding/LD relationship, suitable LD references and genetic architecture assumptions; the intercept is not a universal proof of absence of confounding.'});
for(let q=0;q<2;q++)chart(s,[series('Generating mean',[5,95],q?[1.04,1.76]:[1.4,1.4],C.gray,false,2),series('Binned statistics',data.ldsc.ell,q?data.ldsc.poly:data.ldsc.conf,q?C.orange:C.blue)],70+615*q,180,580,350,{title:q?'B: polygenic component':'A: LD-independent confounding',xt:'LD score ℓᵢ',yt:'Mean χ²',xmin:0,xmax:100,ymin:.8,ymax:2,xformat:'0'});
await eq(s,'ldsim',546,{maxH:49,scale:3});txt(s,'Assumption: the confounding contribution does not increase with LD score.',80,607,1120,34,25,{bold:true,color:C.green});caption(s,21,'Same test statistics as the Q–Q panels; points are bin means, lines are generating means.');
}
// Method comparison remains at every original overview position.
for(const n of [74,75,84,85,86]){
let s=slide('methods_'+n,'Different methods answer different parts of the problem',{replace:n,section:'ACCOUNTING FOR STRUCTURE',sources:['price','kang'],notes:'Table 9 is a teaching comparison. GC rescales statistics and does not change biased effect estimates. LDSC is primarily a summary-statistic diagnostic and inference framework under assumptions, not individual-level removal of confounding. PCs and LMMs can be combined. Standard LMMs account for modeled covariance and do not automatically identify direct effects. Family designs use conditional segregation to target within-family/direct effects under design-specific assumptions. Repeated overview slides are deliberately retained as teaching checkpoints.'});
let rows=[['Approach','Main role','Needs','Important limit'],['PC covariates','Adjust measured ancestry axes','Individual data + PCs','Unmeasured fine structure may remain'],['Mixed model','Model correlated observations','Individual data + GRM','Does not isolate direct effects by itself'],['Genomic control','Rescale test statistics','Association statistics','Effect bias remains; may remove signal'],['LD score regression','Diagnose LD-dependent inflation','Summary statistics + LD','Relies on LD and architecture assumptions'],['Family design','Use within-family transmission','Relatives / parental genotypes','Less information; design assumptions']];
let t=table(s,rows,70,184,1140,380,[214,326,262,338],22);let hi=n===74?4:n===75||n===84?1:2;for(let j=0;j<4;j++)t.getCell(hi,j).fill='#E5F2EF';
txt(s,'Table 9. Choose methods for the target effect and the structure in the data.',80,584,1120,37,26,{color:C.gray});if(n===86)question(s,'Does modelling relatedness identify a direct genetic effect?',628);
}
// Practical PCA: real bigsnpr/bigstatsr calculations, not illustrative screenshots.
{
let s=slide('practical_workflow','Practical PCA with bigsnpr and bigstatsr',{replace:83,section:'PCA IN PRACTICE',sources:['prive','bigsnpr'],notes:notation+' Executed examples use bigsnpr 1.12.21 and bigstatsr 1.6.2. Software input genotypes are N by M. snp_autoSVD returns obj.svd$u for individual unit eigenvectors and obj.svd$d for singular values; predict(obj.svd) returns scores. attr(obj.svd,"subset") identifies retained SNPs. Use snp_projectSelfPCA on held-out rows of the same harmonized matrix; the corresponding bed workflow is bed_autoSVD and bed_projectSelfPCA. QC thresholds and number of PCs are study-specific, not universally 10 or 20. For external cohorts harmonize alleles, variants, centering and scaling; projection shrinkage can matter.'});
table(s,[['Step','Function / diagnostic'],['1. QC and choose fitting samples','Missingness, ancestry context, duplicates / relatives'],['2. Limit LD and estimate PCs','snp_autoSVD() or bed_autoSVD()'],['3. Inspect axes','Scores, SNP loadings, batch and phenotype metadata'],['4. Project other samples','snp_projectSelfPCA() / bed_projectSelfPCA()'],['5. Assess adjustment','Effect estimates and uncertainty across sensible K']],80,178,1120,338,[395,725],25);
await eq(s,'software',548,{maxH:46,scale:3.3});txt(s,'Table 10. Software uses individual rows; obj.svd$u corresponds to the lecture’s V.',80,616,1120,33,25,{color:C.gray});
}
{
let s=slide('ld_failure','A large LD region can dominate the first PC',{after:83,section:'PCA IN PRACTICE',sources:['prive','bigsnpr'],notes:'Figure 31 is computed with bigstatsr::big_randomSVD before filtering and bigsnpr::snp_autoSVD after filtering. Synthetic N=600, M=3000; SNPs 1201-1700 largely copy a single genotype vector independent of group. autoSVD performs LD clumping and iterative long-range-LD detection; 2468 SNPs retained. The demonstrated repair is specific to this simulated LD mechanism and does not guarantee all meaningful structure is preserved. The method is not a batch correction procedure.'});
chart(s,grouped(data.ld.raw,data.ld.ancestry),70,181,560,367,{title:'Before LD filtering',xt:'v₁ coordinate',yt:'v₂ coordinate',xformat:'0.00',yformat:'0.00'});
chart(s,grouped(data.ld.clean,data.ld.ancestry),650,181,560,367,{title:'After snp_autoSVD()',xt:'v₁ coordinate',yt:'v₂ coordinate',xformat:'0.00',yformat:'0.00'});
key(s,['Group A','Group B'],420,552,[C.blue,C.orange]);txt(s,'PC1 group R²: 0.002 → 0.990; 2,468 of 3,000 SNPs retained.',80,601,1120,38,29,{bold:true});caption(s,31,'Same people; the unfiltered PC1 follows the synthetic LD block.');
}
{
let s=slide('ld_loadings','Inspect SNP loadings before trusting a PC',{after:83,section:'PCA IN PRACTICE',sources:['prive','bigsnpr'],notes:'Figure 32 shows all 3000 PC1 loadings from bigstatsr::big_randomSVD in the preceding unfiltered synthetic example. SNP order is by simulated chromosome and position. The concentrated loading region is known to arise from the deliberately introduced correlated block (SNPs 1201-1700). In empirical data an isolated peak calls for investigation, including long-range LD, inversion, quality problems and genuine biology.'});
chart(s,[series('PC1 SNP loading',data.ld.rawLoad.map((_,i)=>i+1),data.ld.rawLoad,C.blue)],80,178,1120,387,{xt:'SNP index (genomic order)',yt:'PC1 loading',xmin:0,xmax:3000,xformat:'0',yformat:'0.00'});
txt(s,'A local loading peak calls for investigation of that genomic region.',80,591,1120,49,30,{bold:true});caption(s,32,'Computed SNP loadings; the synthetic block spans SNPs 1,201–1,700.');
}
{
let s=slide('batch_pc','Check what each PC tracks in the metadata',{after:83,section:'PCA IN PRACTICE',sources:['prive'],notes:'Figure 33 is a separate synthetic example with N=600, M=3000. Batch is assigned independently of ancestry, then a batch-specific allele-dosage frequency shift is introduced across markers. bigstatsr::big_randomSVD produces the axes. Both panels show identical coordinates; only colors change. PC1 R2 with batch=0.991; PC2 R2 with group=0.989. In real data a PC-batch association is a diagnostic, not proof of a technical cause, because recruitment and batch can correlate with ancestry.'});
chart(s,grouped(data.batch.pc,data.batch.ancestry),70,182,560,363,{title:'Color by ancestry group',xt:'v₁ coordinate',yt:'v₂ coordinate',xformat:'0.00',yformat:'0.00'});
chart(s,grouped(data.batch.pc,data.batch.batch,['Batch 1','Batch 2'],[C.green,C.pink]),650,182,560,363,{title:'Same coordinates, color by batch',xt:'v₁ coordinate',yt:'v₂ coordinate',xformat:'0.00',yformat:'0.00'});
key(s,['Group A','Group B'],150,549,[C.blue,C.orange]);key(s,['Batch 1','Batch 2'],720,549,[C.green,C.pink]);question(s,'Would adding this PC fix the underlying genotype-quality problem?',595);caption(s,33,'Separate batch simulation; PC1 follows batch, PC2 follows ancestry group.');
}
{
let s=slide('projection','Fit the axes once, then project the remaining samples',{after:83,section:'PCA IN PRACTICE',sources:['prive','bigsnpr'],notes:'Figure 34 is calculated from the same background genotypes as the running GWAS example. A balanced subset of 480 individuals fits snp_autoSVD; 120 held-out individuals are projected using snp_projectSelfPCA(... )$OADP_proj. Both reference and projected positions use PC scores, not unit eigenvectors. Held-out genotypes are from the same matrix, so allele matching is exact. External-cohort projection additionally needs allele and SNP harmonization and reference centering/scaling. OADP addresses shrinkage under its assumptions; projected points do not refit the reference axes.'});
let a=data.projection,ss=[series('Reference (480)',a.reference.map(v=>v[0]),a.reference.map(v=>v[1]),'#AFBAC0'),series('Projected (120)',a.target.map(v=>v[0]),a.target.map(v=>v[1]),C.green)];ss[1].marker={symbol:'diamond',size:7};
chart(s,ss,80,180,800,408,{xt:'PC1 score',yt:'PC2 score'});key(s,['Reference','Projected'],260,595,['#AFBAC0',C.green]);txt(s,'Reference samples determine the axes.',920,214,280,141,32,{bold:true});txt(s,'Use the same alleles, variants, centering and scaling for projection.',920,405,280,182,29);caption(s,34,'Actual OADP projection with bigsnpr; gray points fit the axes, green points are held out.');
}
{
let s=slide('k_sensitivity','How many PCs? Examine sensitivity of the effect estimate',{after:83,section:'PCA IN PRACTICE',sources:['prive','price'],notes:simNotes+' Figure 35 repeats the null-SNP regression with K=0,1,2,5,10,20 PCs. K=1 captures the only simulated ancestry axis; extra PCs bring little change here. This example cannot specify K for another study. Choose candidate K values using the study design and diagnostics, not the smallest association P value. Inspect effect estimates, uncertainty, residual structure and relevant external or family evidence.'});
let rr=data.running.null,ss=[series('Truth',[0,20],[0,0],C.gray,false,1.5),series('Estimate',rr.map(r=>r.K),rr.map(r=>r.beta),C.blue,false,3)];rr.forEach(r=>ss.push(series('95% CI, K='+r.K,[r.K,r.K],[r.low,r.high],C.blue,false,2)));chart(s,ss,80,183,780,407,{xt:'Number of PCs K',yt:'Estimated null-SNP effect',xmin:-1,xmax:21,ymin:-.3,ymax:.6,xformat:'0'});
txt(s,'The estimate stabilizes after the first PC in this simulation.',905,218,290,175,31,{bold:true});txt(s,'Choose K using diagnostics and the study design.',905,456,290,133,29);caption(s,35,'The running example: point estimates with 95% confidence intervals; true effect = 0.');
}
// Family diagrams deliberately distinguish correlation from transmission.
{
let s=slide('family_covariance','Relatives create correlated observations',{replace:88,section:'RELATEDNESS AND DIRECT EFFECTS',sources:['kang'],notes:'Figure 36 is a small, schematic non-inbred pedigree: two unrelated parents and two full siblings. The expected additive relationship matrix has diagonal 1, parent-child entries 0.5, sibling entry 0.5, and unrelated-parent entry 0. Realized genomic relatedness varies around pedigree expectation, especially between siblings. A mixed model uses a relationship/kinship matrix to model residual genetic covariance. This does not, by itself, separate direct and indirect genetic effects.'});
let fa=shape(s,'rect',195,229,55,55,C.blue),mo=shape(s,'ellipse',425,229,55,55,C.orange);line(s,250,256,425,256);line(s,336,256,336,364);line(s,220,364,455,364);line(s,220,364,220,419);line(s,455,364,455,419);shape(s,'rect',194,419,55,55,C.green);shape(s,'ellipse',428,419,55,55,C.pink);txt(s,'Father',165,174,135,45,27);txt(s,'Mother',400,174,135,45,27);txt(s,'Child 1',168,494,150,40,27);txt(s,'Child 2',402,494,150,40,27);
let vals=[['','F','M','C1','C2'],['F','1','0','0.5','0.5'],['M','0','1','0.5','0.5'],['C1','0.5','0.5','1','0.5'],['C2','0.5','0.5','0.5','1']];let t=table(s,vals,680,227,500,280,[100,100,100,100,100],26);for(let i=1;i<5;i++)for(let j=1;j<5;j++){let v=Number(vals[i][j]);t.getCell(i,j).fill=v===1?'#A3D4E8':v===.5?'#D4E9F2':'#FFFFFF';}
txt(s,'Expected additive relationship matrix',672,549,518,70,29,{bold:true});caption(s,36,'A simple pedigree and its expected relationship heatmap (diagonal = 1).');
}
{
let s=slide('transmission','Parental transmission answers a different question',{replace:89,section:'RELATEDNESS AND DIRECT EFFECTS',sources:['family'],notes:'Figure 37 is a pedagogical directed diagram, not a fitted causal model. Parental genotype influences transmitted child genotype and may influence the child environment through indirect parental effects. A trio design conditions on parental genotypes to exploit segregation of transmitted alleles. Direct-effect interpretation still depends on design and assumptions, including effects of siblings, assortative mating, selection and population structure. The following trio equation is a simplified teaching regression, not the exact estimator in Guan et al.'});
let par=txt(s,'Parental genotypes',470,201,370,66,34,{bold:true,align:'center'}),ch=txt(s,'Transmitted alleles\nin the child',80,357,380,118,32,{bold:true,align:'center'}),env=txt(s,'Family environment',813,357,385,85,32,{bold:true,align:'center'}),phen=txt(s,'Child phenotype π',470,533,380,68,34,{bold:true,align:'center'});
for(const [from,to,col] of [[par,ch,C.blue],[par,env,C.orange],[ch,phen,C.blue],[env,phen,C.orange]])s.shapes.connect(from,to,{kind:'straight',line:{fill:col,width:3},tail:{type:'arrow'}});
txt(s,'Direct pathway',93,542,265,50,27,{color:C.blue});txt(s,'Indirect pathway',917,533,285,59,27,{color:C.orange});caption(s,37,'Conditioning on parental genotypes helps distinguish transmitted and parental pathways.');
}
{
let s=slide('tractor_diagram','Tractor-Mix combines local ancestry with relatedness',{after:91,section:'RELATEDNESS AND DIRECT EFFECTS',sources:['tan'],notes:'Figure 38 is a teaching diagram. At the marked SNP, one allele is assigned to reference ancestry 1 and one to reference ancestry 2; local ancestry can differ elsewhere despite the same global fraction. Tractor-Mix models ancestry-specific dosages and background relatedness; the joint test in the two-ancestry setting has two degrees of freedom. An ancestry-specific model may gain power under effect heterogeneity but can lose power relative to a shared-effect model when effects are homogeneous. Diagram is not a reconstruction of an observed genotype.'});
chromosomes(s,223,{offset:true});line(s,890,200,890,382,C.ink,3,true);txt(s,'Tested SNP',819,386,180,48,28,{bold:true});txt(s,'Local ancestry-specific dosage',80,471,480,87,33,{bold:true});arrow(s,560,506,680,506,C.ink);txt(s,'Ancestry-specific effects\n+ a relatedness model',734,465,466,115,32,{bold:true});caption(s,38,'Local ancestry at the tested locus supplies information absent from a global proportion.');
}
// Replace dense numerical summaries with editable data plots; retain the tables in the appendix.
{
let s=slide('rare_plot','Rare-variant structure can survive common-PC adjustment',{replace:72,section:'DIAGNOSING INFLATION',sources:['rare'],notes:'Figure 39 plots the exact genomic inflation values from the source summary table. Trait: birthplace; N=279390 UK-born participants of inferred European ancestry (within a broader analysis of 306991 exomes). Adjustments: none 6.69; 10 common PCs 1.57; 10 rare PCs 1.31; 40 common plus 30 rare PCs 1.22; 30 haplotype components 1.01. The source still observed false-positive loci despite a near-one genome-wide summary. These are not directly comparable causal-effect estimates, and lambda depends on the setting. Original table retained in the appendix.'});
let rows=[['None',6.69],['10 common PCs',1.57],['10 rare PCs',1.31],['40 common + 30 rare PCs',1.22],['30 haplotype components',1.01]];
let ss=[series('Reference λ=1',[1,1],[.5,5.5],C.gray,false,1.5)];rows.forEach((r,i)=>{let z=series(r[0],[r[1]],[5-i],i===4?C.green:C.blue);z.marker.size=10;z.dataLabelOverrides=[{idx:0,text:r[0]+'  '+r[1].toFixed(2),position:'right',textStyle:{typeface:'Calibri',fontSize:23,fill:C.ink}}];ss.push(z);});chart(s,ss,90,172,1080,410,{xt:'Genomic inflation factor λGC',yt:'',xmin:0,xmax:8.3,ymin:.4,ymax:5.7});
txt(s,'Near-one genome-wide inflation does not certify every locus.',80,599,1120,43,31,{bold:true,color:C.green});caption(s,39,'Birthplace association: reported λ values under progressively different adjustments.');
}
{
let s=slide('moba_forest','Parental adjustment attenuates some SNP associations',{replace:93,section:'RELATEDNESS AND DIRECT EFFECTS',sources:['moba'],notes:'Figure 40 plots the exact summary values in the previous table: proportional attenuation of SNP effect estimates in the same children after adjusting for parental genotypes. Height N=23786:11% (95% CI8-15); educational achievement N=41761:23% (18-28); sleep N=24376:29% (9-49); depressive symptoms N=18701:16% (3-28). SNP sets come from external GWAS and confidence intervals are based on jackknife estimates as reported in Corfield et al. (2026), not standard-error reconstruction from the rounded bounds. These are not percentage reductions in SNP heritability. The original table remains in the appendix.'});
let rows=[{label:'Height; N = 23,786',beta:11,low:8,high:15,color:C.blue},{label:'Educational achievement; N = 41,761',beta:23,low:18,high:28,color:C.green},{label:'Sleep; N = 24,376',beta:29,low:9,high:49,color:C.orange},{label:'Depressive symptoms; N = 18,701',beta:16,low:3,high:28,color:C.pink}];
chart(s,intervalSeries(rows,[0]),80,182,1120,407,{xt:'Attenuation of SNP effects (%) with 95% CI',yt:'',xmin:-5,xmax:55,ymin:.3,ymax:4.8,xformat:'0'});
txt(s,'Parental adjustment changes the estimated effects in the same children.',80,602,1120,38,29,{bold:true});caption(s,40,'MoBa: proportional effect attenuation; intervals and sample sizes as reported.');
}
{
let s=slide('appendix_start','Appendix: alternative examples and numerical details',{after:94,section:'APPENDIX',notes:'The raw-correlation illustration, abstract two-individual PCA example, and original All of Us, rare-variant and MoBa tables are retained here. This implements the selected focused PCA example and figure replacements while keeping the source teaching material available. General duplicate removal (#3) was explicitly excluded by the user.'});
txt(s,'Raw-vector correlations\nAbstract two-individual PCA derivation\nOriginal numerical summaries behind the new figures',100,233,1080,280,36);
}
// Enlarge selected original panels, retaining the complete originals in the appendix.
{
let s=slide('ukb_panels','Genetic axes in UK Biobank',{replace:40,section:'MEASURING STRUCTURE',sources:['prive22'],notes:'Figure 10 enlarges PC1/PC2 and PC3/PC4 from the supplied lecture figure without changing any points, axes or group colors. The complete four-panel figure is retained in the appendix. Original source citation: Privé et al. (2022), American Journal of Human Genetics, https://doi.org/10.1016/j.ajhg.2021.11.008 .'});
await pic(s,B+'/original-39-0.png',80,202,440,351,'Figure 10. Original UK Biobank PC1/PC2 panel',{left:0,top:0,right:.582,bottom:.495});
await pic(s,B+'/original-39-0.png',544,202,440,351,'Original UK Biobank PC3/PC4 panel',{left:.421,top:0,right:.156,bottom:.495});
await pic(s,B+'/original-39-0.png',1006,254,194,266,'Original UK Biobank ancestry-group legend',{left:.85,top:.345,right:0,bottom:.335});
txt(s,'Additional axes can reveal structure within the broad pattern of PC1 and PC2.',80,592,1120,48,29,{bold:true});caption(s,10,'Enlarged source panels; the complete four-panel figure is in the appendix.');
}
{
let s=slide('kg_panels','Genetic axes in 1000 Genomes',{replace:41,section:'MEASURING STRUCTURE',notes:'Figure 11 retains original source-lecture PCA scores and reference population labels, enlarging the first two panels. No genotype coordinates were reconstructed or invented. The complete original four-panel figure is retained in the appendix. Source artifact: Population_Structure_20250902.pptx, supplied 2025 lecture.'});
await pic(s,B+'/original-40-0.png',80,226,540,334,'Figure 11. Original 1000 Genomes PC1/PC2 panel and legend',{left:0,top:0,right:.5,bottom:.5});
await pic(s,B+'/original-40-0.png',660,226,540,334,'Original 1000 Genomes PC3/PC4 panel and legend',{left:.5,top:0,right:0,bottom:.5});
txt(s,'The meaning of each axis depends on the samples and variants used to fit it.',80,592,1120,48,29,{bold:true});caption(s,11,'Enlarged source-lecture panels; the remaining axes are in the appendix.');
}
{
let s=slide('tree_detail','Trees summarize structure, but cannot show every migration',{replace:18,section:'MEASURING STRUCTURE',sources:['li','jakobsson'],notes:'Figure 8 retains the supplied unrooted population tree on the left and enlarges a selected part of the original rooted tree on the right. The full rooted tree remains on the preceding slide. No branch lengths, topology, leaf names or colors are reconstructed. Original references: Jakobsson et al. (2008), Nature, https://doi.org/10.1038/nature06742; Li et al. (2008), Science, https://doi.org/10.1126/science.1153717 .'});
await pic(s,B+'/original-16-0.png',80,211,500,405,'Figure 8a. Original unrooted tree');
await pic(s,B+'/original-16-1.png',743,199,395,409,'Figure 8b. Enlarged selected clade in the original rooted tree',{left:.57,top:.142,right:.09,bottom:.523});
txt(s,'Selected rooted-tree detail',683,165,510,40,27,{bold:true});caption(s,8,'Original trees; full rooted-tree context is on the preceding slide.');
}
// Full notes and LaTeX sources travel with the authored slides.
for(const s of p.slides.items){let m=s.meta;let notes=m.notes+'\n\n'+(m.sources.length?'[Sources]\n'+m.sources.map(k=>ref[k].join('\n')).join('\n\n'):'');if(m.equations.length)notes+='\n\n[LaTeX equations]\n'+m.equations.map(k=>'('+E[k].number+') '+E[k].latex).join('\n');s.speakerNotes.textFrame.setText(notes);}
return manifest;
}
